@startuml Crypto Credits Technical Architecture

!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v13.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/ApplicationIntegration/APIGateway.puml
!include AWSPuml/Containers/ElasticKubernetesService.puml
!include AWSPuml/Blockchain/Blockchain.puml
!include AWSPuml/Database/Database.puml
!include AWSPuml/Analytics/ManagedStreamingforApacheKafka.puml

left to right direction

APIGateway(apiGateway, "API Gateway", "External API Patterns")
ElasticKubernetesService(creditCrytoService, "Credit Crypto Service", "Saga Pattern")
ElasticKubernetesService(blockchainService, "Core", "Block chain client")
ManagedStreamingforApacheKafka(kafka, "Kafka", "Message Style Pattern")
Database(databaseBlockchain, "Database", "Postgres Database")
Blockchain(blockchain, "blockchain", "blockchain")
ElasticKubernetesService(exportService, "tx exporter", "Last mile service")
ElasticKubernetesService(analyticsService, "Analytics", "Last mile service")
ElasticKubernetesService(auditService, "Audit", "Last mile service")
Database(databaseBusinessRequirements, "Database", "Postgres Database")
component "External Platform" as externalapp <<service layer>>

apiGateway --> creditCrytoService : JSON message
creditCrytoService --> blockchainService : JSON messages
creditCrytoService --> kafka : JSON messages
blockchainService --> blockchain : Tx messages
blockchainService --> databaseBlockchain : Tx messages
kafka --> exportService : JSON messages
kafka --> analyticsService : JSON messages
kafka --> auditService : JSON messages
exportService --> externalapp : Tx messages
exportService --> databaseBusinessRequirements : Tx messages
analyticsService --> databaseBusinessRequirements : Tx messages
auditService --> databaseBusinessRequirements : Tx messages

@enduml