# This workflow will test common endpoints project

name: common-endpoint-ci

on:
  push:
    branches:
      - "dev"
    paths:
      - "libs/common-endpoints/**"
      - ".github/workflows/common-endpoints.yaml"
  pull_request:
    branches:
      - "dev"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.x
      - name: Cache Go Build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-goce-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-goce-
      - name: Test lib common-endpoints
        run: |-
          cd libs/common-endpoints
          go test -race ./...